### ISSUE TITLE
Upgrade to mybatis-thymeleaf 1.0.2

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#450]
https://github.com/mybatis/thymeleaf-scripting/milestone/5?closed=1

This change includes bug fix.

* mybatis/thymeleaf-scripting#55

### Tasks

- [x] Apply snapshot version
- [x] Apply workaround for spring-projects/spring-boot#21626 #456
- [ ] Apply release version
